# 擷取模式: backfill (歷史回填) 或 daily (每日更新)
mode: 'backfill'

# 廣告帳戶 ID 列表 (請填入真實的 act_... ID)
ad_account_ids:
  #- 'act_'

# 歷史數據抓取的時間範圍 (僅在 backfill 模式下使用)
date_range:
  start_date: '2025-09-18'
  end_date: '2025-09-18'
